# Generated by Django 5.0.6 on 2024-07-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'allowed_table',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='title', max_length=64)),
                ('description', models.TextField()),
                ('author_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sql_query', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('execute_query', 'Can execute queries')],
            },
        ),
        migrations.CreateModel(
            name='AllowedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_builder_app.allowedtable')),
            ],
            options={
                'unique_together': {('table', 'name')},
            },
        ),
    ]
