# Generated by Django 4.2.5 on 2024-05-20 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=50, null=True)),
                ('datatables_columns_config', models.JSONField(null=True)),
                ('highcharts_config', models.JSONField(null=True)),
                ('query', models.TextField(null=True)),
                ('fields', models.TextField(null=True)),
                ('context', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='SQLChatModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_context', models.TextField(null=True)),
                ('dashboard_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_builder_app.dashboardmodel', to_field='uuid')),
            ],
            options={
                'db_table': 'sql_chat',
            },
        ),
        migrations.CreateModel(
            name='MainChatModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat', models.JSONField()),
                ('dashboard_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_builder_app.dashboardmodel', to_field='uuid')),
            ],
            options={
                'db_table': 'main_chat',
            },
        ),
    ]
