# Generated by Django 4.2.5 on 2024-05-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('apply_permanent_images', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mailing_campaign',
            },
        ),
        migrations.CreateModel(
            name='MailingFactory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('white_label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('campaign', models.CharField(max_length=255)),
                ('permanent', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=255)),
                ('href', models.TextField(default='')),
                ('extension', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'mailing_factory',
            },
        ),
        migrations.CreateModel(
            name='MailingHTML',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('white_label', models.CharField(max_length=255)),
                ('csv_data', models.TextField()),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailing_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_manager_app.mailingcampaign')),
            ],
            options={
                'db_table': 'mailing_html',
            },
        ),
    ]
