# Generated by Django 4.2.1 on 2023-06-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AdminMultikrd', 'AdminMultikrd'), ('AdminMarketing', 'AdminMarketing'), ('UserMarketing', 'UserMarketing')], default='UserMarketing', max_length=15, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='AllowedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.allowedtable')),
            ],
            options={
                'unique_together': {('table', 'name')},
            },
        ),
    ]
