# Generated by Django 4.2.1 on 2023-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_allowedtable_alter_user_role_allowedfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=64),
        ),
    ]
