# Generated by Django 4.2.2 on 2023-06-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_query_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedfield',
            name='description',
            field=models.TextField(default='Without description, is Implicit in field name.'),
            preserve_default=False,
        ),
    ]
