# Generated by Django 4.2.5 on 2023-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_allowedfield_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('table_template', models.TextField()),
                ('chart_template', models.TextField()),
                ('chat_history', models.JSONField()),
            ],
        ),
    ]
