# Generated by Django 4.2.5 on 2023-10-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='javasctipt_code',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
