# Generated by Django 4.2.5 on 2024-04-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_process_javasctipt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
