# Generated by Django 4.2.5 on 2024-03-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingHTML',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('white_label', models.CharField(max_length=255)),
                ('csv_data', models.TextField()),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailing_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='html_manager.mailingcampaign')),
            ],
        ),
    ]
