# Generated by Django 4.2.5 on 2024-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='apply_permanent_images',
            field=models.BooleanField(default=False),
        ),
    ]
