# Generated by Django 5.0.3 on 2024-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingFactory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('white_label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('campaign', models.CharField(max_length=255)),
                ('permanent', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
