# Generated by Django 4.2.5 on 2024-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingfactory',
            name='extension',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
