# Generated by Django 4.2.5 on 2024-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_mailingfactory_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingfactory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
