# Generated by Django 4.2.5 on 2024-04-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_alter_mailingfactory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingfactory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
